# Generated by Django 5.1.5 on 2025-02-20 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feast', '0002_restaurantprofile_number_of_tables_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablebooking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=50),
        ),
    ]
