# Generated by Django 5.1.5 on 2025-02-21 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feast', '0003_alter_tablebooking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='menu_image',
            field=models.ImageField(blank=True, upload_to='menu'),
        ),
    ]
